version: "3"
services:
  ide-backend:
    image: "ide-backend:latest"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
    command: "npm start"
    networks: 
      - ide-backend-network
    depends_on:
      - "db"

  db:
    image: postgres
    restart: always
    networks: 
      - ide-backend-network
    environment:
      POSTGRES_USER: tarunluthra
      POSTGRES_DB: idedb
      POSTGRES_PASSWORD: iamsherlocked

networks:
    ide-backend-network:
        external:
            name: ide-backend-network
